---
- hosts: all
  tasks:
    - name: open firewall tcp443
      firewalld:
        service: https
        permanent: yes
        state: enabled
        
    - name: open firewall tcp80
      firewalld:
        service: http
        permanent: yes
        state: enabled
        
    - name: restart firewalld
      service: name=firewalld state=restarted
        
    - name: install httpd
      yum: name=httpd update_cache=yes state=latest
      
    - name: start httpd
      service: name=httpd state=restarted
