---
- hosts: all
  tasks:
    - name: run updates
      yum: name=* state=latest
      
    - name: install pexpect
      yum: name=pexpect update_cache=yes state=latest
    
    - name: install onapp repo
      command: rpm -Uvh http://rpm.repo.onapp.com/repo/onapp-repo-6.2.noarch.rpm
      ignore_errors: yes
        
    - name: install onapp installer
      yum: name=onapp-hv-install update_cache=yes state=latest
        
    - name: install onapp kvm
      expect:
        command: /onapp/onapp-hv-install/onapp-hv-kvm-install.sh
        responses:
          'Do you wish to proceed yes/no [NO] ?' : 'yes'
