---
- hosts: all
  gather_facts: no
  tasks:
  - name: Restart
    - shell: shutdown -r now

  - name: Wait
    wait_for_connection:
      timeout: 300
      
      - name: uptime
    # And finally, execute 'uptime' when the host is back.
    - shell: uptime
