---
  hosts: all
    tasks:

- name: Reboot a host and wait for it to return
    - shell: shutdown -r now
    
- name: Wait 300 seconds, but only start checking after 60 seconds
  wait_for_connection:
    delay: 60
    timeout: 300

- name: PING
    
    # Now we will run a local 'ansible -m ping' on this host until it returns.
    # This works with the existing ansible hosts inventory and so any custom ansible_ssh_hosts definitions are being used
    - local_action: shell ansible -u {{ ansible_user_id }} -m ping {{ inventory_hostname }}
      register: result
      until: result.rc == 0
      retries: 30
      delay: 10
- name: uptime
    # And finally, execute 'uptime' when the host is back.
    - shell: uptime
